version: '2'

services:
  app:
    image: registry.spin.nersc.gov/bpb20/metatlas_lims-app:2020-01-17-13-53
    cap_drop:
        - ALL
    volumes:
      - app.metlims-nersc:/usr/local/labkey/files
  db:
    image: postgres:12
    stdin_open: true
    tty: true
    volumes:
      - db.metlims-nersc:/var/lib/postgresql/data
    secrets:
      - mode: '0444'
        uid: '55710'
        gid: '55710'
        source: db.metlims-nersc.postgres_password2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: /run/secrets/db.metlims-nersc.postgres_password2
      POSTGRES_DB: "labkey"
    cap_drop:
        - ALL
    cap_add:
        - CHOWN
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
  db-dump:
    image: registry.spin.nersc.gov/pub/postgres-pg_dump:12-alpine
    stdin_open: true
    tty: true
    volumes:
      - /global/cfs/cdirs/metatlas/projects/lims_backups/pg_dump/:/pg_dump
    secrets:
      - mode: '0444'
        uid: '55710'
        gid: '55710'
        source: db.metlims-nersc.postgres_password2
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: /run/secrets/db.metlims-nersc.postgres_password2
      POSTGRES_DATABASE: labkey
      POSTGRES_DUMP_DIR: /pg_dump
      POSTGRES_DUMP_FILE_BASE: ${RANCHER_ENVIRONMENT}-metlims-dump.sql.gz
      POSTGRES_DUMP_RETAIN_DAYS: '14'
      TZ: US/Pacific
    cap_drop:
        - ALL
    user: 55710:55710
    labels:
      io.rancher.container.pull_image: always
      cron.schedule: 0 0 11 * * *
      io.rancher.container.start_once: 'true'

volumes:
  app.metlims-nersc:
    driver: rancher-nfs
    external: true
  db.metlims-nersc:
    driver: rancher-nfs
    external: true
secrets:
  db.metlims-nersc.postgres_password2:
    external: true
