version: '2'

services:
  app:
    image: registry.spin.nersc.gov/bpb20/metatlas_lims-app:2019-07-18-20-03
    ports:
      - "60023:8080"
      - "587:587"
      - "465:465"
      - "25:25"
    links:
      - "db:database"
    cap_drop:
        - ALL
  db:
    image: postgres:12
    stdin_open: true
    tty: true
    volumes:
      - db.metlims-nersc:/var/lib/postgresql/data
    secrets:
      - mode: '0444'
        uid: '55710'
        gid: '55710'
        source: db.metlims-nersc.postgres_password2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: /run/secrets/db.metlims-nersc.postgres_password2
      POSTGRES_DB: "labkey"
    ports:
      - "5432:5432"
    cap_drop:
        - ALL
    cap_add:
        - CHOWN
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID

volumes:
  db.metlims-nersc:
    driver: rancher-nfs
secrets:
  db.metlims-nersc.postgres_password2:
    external: true

