version: '2'

services:
  app:
    image: registry.spin.nersc.gov/bpb20/labkey-app:2019-07-17
    ports:
      - "50033:8080"
      - "587:587"
    links:
      - "db:database"
    volumes:
      - /project/projectdirs/metatlas:/project_metatlas:ro
      - /projectb/sandbox/metatlas:projectb_metatlas:ro
  db:
    image: postgres:10
    stdin_open: true
    tty: true
    volumes:
      - db.metlims-nersc:/var/lib/postgresql/data
    secrets:
      - mode: '0444'
        uid: '0'
        gid: '0'
        source: db.metlims-nersc.postgres_password
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "mypassword"
#      POSTGRES_DB: "labkey"
    ports:
      - "5432:5432"
volumes:
  db.metlims-nersc:
    driver: rancher-nfs

secrets:
  db.metlims-nersc.postgres_password:
    external: true
