apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: u-kjpiuiv26t
    field.cattle.io/ingressState: '{"bGIvbGltcy9sYi5saW1zLnByb2R1Y3Rpb24uc3ZjLnNwaW4ubmVyc2Mub3JnLy84MDgw":"deployment:lims:labkey","bGIvbGltcy9tZXRhdGxhcy5uZXJzYy5nb3YvLzgwODA=":"deployment:lims:labkey","bWV0YXRsYXMtc2hvcnQtY2VydA==":"lims:metatlas-short-cert"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["128.55.206.106"],"port":80,"protocol":"HTTP","serviceName":"lims:labkey","ingressName":"lims:lb","hostname":"lb.lims.production.svc.spin.nersc.org","allNodes":true},{"addresses":["128.55.206.106"],"port":443,"protocol":"HTTPS","serviceName":"lims:labkey","ingressName":"lims:lb","hostname":"metatlas.nersc.gov","allNodes":true}]'
    nersc.gov/clustername: production
    nersc.gov/serveralias: svc
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
  name: lb
  selfLink: /apis/extensions/v1beta1/namespaces/lims/ingresses/lb
spec:
  rules:
  - host: lb.lims.production.svc.spin.nersc.org
    http:
      paths:
      - backend:
          serviceName: labkey
          servicePort: 8080
  - host: metatlas.nersc.gov
    http:
      paths:
      - backend:
          serviceName: labkey
          servicePort: 8080
  tls:
  - hosts:
    - metatlas.nersc.gov
    secretName: metatlas-cert
status: {}
